name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set output variables
        id: vars
        run: |
          VERSION=$(python -c "import src.pra_todos_verem; print(src.pra_todos_verem.__version__)")
          echo ::set-output name=TAG::${VERSION}
          echo ::set-output name=COMMIT::${{ github.sha }}
          echo ::set-output name=BRANCH::${{ github.ref }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: docker.io/fberanizo/pra-todos-verem-data-collection:${{ steps.vars.outputs.TAG }}
          build-args: |
            COMMIT=${{ steps.vars.outputs.COMMIT }}
            BRANCH=${{ steps.vars.outputs.BRANCH }}
